### ISSUE TITLE
Link to "PRIDE Archive dataset license" not working. Version 2.5.0

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/px-submission-tool#103]
<img width="404" alt="Capture" src="https://user-images.githubusercontent.com/38863291/92216222-ef407600-ee8d-11ea-87f4-52babb8aacf6.PNG">

**Comment by fionacalico** [comment]
Is this still an issue? I don't see any box where I'm able to 'accept PRIDE Archive dataset license. Is there any way around this? Thanks

**Comment by fionacalico** [comment]
Hi,
I've got it to work with windows. However, I still couldn't get it working
on Mac but it's not an issue now.
Thanks,
Fiona

**Comment by selvaebi** [comment]
are you using the latest version , and also can you let me know what version of mac are you using

**Comment by fionacalico** [comment]
Latest version and also the latest version of Big Sur

**Comment by selvaebi** [comment]
Sorry and you java version as well please

**Comment by fionacalico** [comment]
The latest, I just downloaded it

**Comment by selvaebi** [comment]
it seems everything is working fine foer the latest versions. can you pease paste screen shots of all above versions and how you are running it and the final screen

**Comment by fionacalico** [comment]
Hi,
It worked in the end. It's just that the box was not visible for the
submission but I just clicked on the space next to it and it worked.
Thanks,
Fiona
