### ISSUE TITLE
Data submission issue

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/px-submission-tool#104]
User meets an issue when submitting proteomic data through ProteomeXchange submission tool.
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=429676

**Comment by selvaebi** [comment]
It means the withing the mzid file the named files are not peak files.

**Comment by ypriverol** [comment]
This means @davco6 exactly what @selvaebi said.

**Comment by davco6** [comment]
ok, thanks
