### ISSUE TITLE
User cannot go through the last step of PX submission tool

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/px-submission-tool#106]
Helle

One user is using the last version of the PX submission tool 2.5.1, and cannot go through the last of the PX submission tool, since the button is faded.

https://helpdesk.ebi.ac.uk/Ticket/Attachment/8481521/5311535/Screen%20Shot%202020-09-10%20at%2019.32.07.png
https://helpdesk.ebi.ac.uk/Ticket/Attachment/8483026/5312470/Screen%20Shot%202020-09-11%20at%2009.36.42.png

Regards,
David

**Comment by selvaebi** [comment]
the checkbox is faded for windows particular version i guess, i tested on my personal windows computeri can see hte checkbox.
