### ISSUE TITLE
Link to "How to manually set the proxy details" not working

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/px-submission-tool#108]
Link to "How to manually set the proxy details" not linked to the actual page of the manual about how to set the proxy details.
<img width="182" alt="Capture" src="https://user-images.githubusercontent.com/38863291/96256864-5125ec80-0fb1-11eb-9430-76eecaadbfc9.PNG">

**Comment by selvaebi** [comment]
will be updated in next release.
