### ISSUE TITLE
Submission stop it during the checksum check:

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/px-submission-tool#111]
Hello,
one user is having some troubles with the PX submission tool during the step 3 (checking files)

The user is using the latest version of the PX submission tool 2.5.1

Here it is the screenshot of the error:
https://helpdesk.ebi.ac.uk/Ticket/Attachment/8647056/5415420/Pride_submission_timsTOF_MQ.JPG
and the log file
https://helpdesk.ebi.ac.uk/Ticket/Attachment/8658599/5422707/px_submission.log

Regards,
David

**Comment by selvaebi** [comment]
it is due to a malformed zip file. They are not properly zipped.
