### ISSUE TITLE
Submission can not go through the step number 10

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/px-submission-tool#113]
Hello,

one user is having some troubles with the PX-submission tool (v2.5.1), doing a partial submission the user cannot go through the step number 10 since the "Submit" button is blocked.

I attach the log file and the screenshot of the issue
![image003](https://user-images.githubusercontent.com/38863291/98096370-95572f00-1e83-11eb-947f-6ebe118e83af.jpg)
[px_submission.log](https://github.com/PRIDE-Archive/px-submission-tool/files/5486965/px_submission.log)

Here you can find more details:
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=457668

**Comment by emassign** [comment]
Hi, I'm having the same problem (using version 2.5.2)
