### ISSUE TITLE
"aspera/etc/aspera.conf" does not work since you introduced the Aspera file transfer

### ISSUE THREAD

**Issue by TKMassSpec** [PRIDE-Archive/px-submission-tool#117]
This is a bug report that comes with an easy fix at the end! I doubt that anyone ever successfully transferred data using the px-submission-tool with Aspera. I mean not in the way that PRIDE guys sent credentials for the ASPERA Command line and the people use the CLI tool, but via the default configuration of the java-based px-submission-tool.  I struggled for years with the tool and it never worked with Aspera. It always used slow and instable FTP transfer as a fallback mode. We observed that the CLI tool for Aspera works fine and just looked into the aspera.conf. We copied the aspera.conf from the CLI tool to the aspera/etc folder of the px-submission-tool and overwrote the default config file and now guess what happens: It worked and the file transfer is awesome fast ...and I am furious how this could be?! Again, it took me years to find the issue.  With the buggy aspera.conf the software always responded that Port 22 and UDP33001 in the network/firewall settings needs to enable outbound traffic and the user should contact the system administrator. These ports are not blocked in any firewall. With a network analysis tool we could see that the px-submission-tool has never been made a request to these ports! The default aspera.conf that comes with the px-submission-tool DOES NOT WORK (it never did) and includes lines 4-7 for the central_server setup. Those do the mess!
How to fix the issue:
Delete lines 4-7 for the "central_server" settings and the Aspera transfer works like a charm! 
Make sure that you change the aspera.conf for the next release, and you will make lots of angry users happy!

**Comment by selvaebi** [comment]
Thanks for your suggestion and good to know it worked for you. But our Aspera seems to be working fine for our users using the latest tool with the same config.
