### ISSUE TITLE
Unexplained mzTab validation error

### ISSUE THREAD

**Issue by vrkosk** [PRIDE-Archive/px-submission-tool#118]
I'm trying to find out why an mzTab file is being rejected. The data file is from a customer. I'm using PRIDE Submission Tool 2.5.2, and:

- Logged in to my PRIDE account
- Choose Complete Submission
- Dataset details on page 2/11 are "test project for mztab validation" etc.
- On page 3/11, I've added the mzTab file and a dummy .wiff file. The latter is just to avoid an error about a missing raw file.

The program reports "The following files ARE NOT VALID: S15(2).mztab". There is no other detail about what is not valid. This is the same problem the customer found.

When I look at the px_submission.log file, there is no more detail, just this:

2021-03-30 14:51:35,397 ERROR [pool-1-thread-9] u.a.e.p.d.m.p.MzTabParser [MzTabParser.java:118] An error occurred while parsing a section of the mzTab file, 'The current subproduct DOES NOT VALIDATE'
2021-03-30 14:51:35,397 ERROR [pool-1-thread-9] u.a.e.p.g.t.FileScanAndValidationTask [FileScanAndValidationTask.java:441] Invalid mzTab file 'S15(2).mztab', MAIN ERROR: 'The current subproduct DOES NOT VALIDATE'. PLEASE, REFER TO LOG FILES FOR MORE DETAILED INFORMATION

I cannot see any other log files it could be referring to. Looking at the files shipped with PRIDE Submission Tool, it seems to be using version 3.0.5 of jmztab. I've downloaded jmztab-modular-cli 3.0.2 from:

http://www.ebi.ac.uk/pride/resources/tools/jmztab/latest/jmztab-modular-cli.zip

When I run the validation command, the tool reports no errors:

java -jar .\mzTabCLI.jar -level Info -check inFile=path/to/S15(2).mztab

However, if I deliberately introduce syntax errors to the file, mzTabCLI.jar continues to report that the file is valid, so I don't know how reliable this check is. I can't download the binary for jmztab-modular-cli 3.0.9, because it's behind a password prompt.

So, the problems are:

- How do I increase logging level in the PRIDE Submission Tool to see what it thinks is not valid with the mzTab file?
- Is there a reliable validator available for download somewhere? Or can I somehow use the code embedded in the PRIDE Submission Tool and run it from the command line?
- Can the actual reason for validation error be displayed in the GUI?

**Comment by selvaebi** [comment]
Hi can you provide the mztab file you are using for validation.

**Comment by vrkosk** [comment]
Could you use any invalid mzTab file? My bug report isn't about the data file, it's about logging and error messages.

**Comment by selvaebi** [comment]
Can you provide the whole log file of yours

**Comment by vrkosk** [comment]
[px_submission.log](https://github.com/PRIDE-Archive/px-submission-tool/files/6270625/px_submission.log)

**Comment by selvaebi** [comment]
Your log file shows the error "2021-03-30 14:51:35,397 ERROR [pool-1-thread-9] u.a.e.p.d.m.m.DefaultMzTabSectionValidator [DefaultMzTabSectionValidator.java:35] Missing title in mzTab metadata section!"

**Comment by vrkosk** [comment]
Aha, I missed the error! Thanks. My first question is answered.

**Comment by selvaebi** [comment]
* You can just use the submission tool to log out the errors for you instead of doing it manually in command line. 
* Sorry Its a native code and its designed to log into the log file , cant put into GUI as it will cause cumbersome.
