### ISSUE TITLE
URL for proxy settings help is broken

### ISSUE THREAD

**Issue by vrkosk** [PRIDE-Archive/px-submission-tool#119]
I'm using PRIDE Submission Tool 2.5.2 from behind an HTTP proxy. When I try to log, in there is a helpful prompt with a link:

"Are you connected to the Internet via a proxy?"

The link goes to: https://www.ebi.ac.uk/pride/markdownpage/documentationpage#PX-proxy-settings

Unfortunately, that page has no proxy settings help. DuckDuckGo finds the page https://www.ebi.ac.uk/node/13299/view, but it's been deleted from ebi.ac.uk. The search engine showed the first few sentences of the page text, so I could see the configuration is in config/config.props.

**Comment by selvaebi** [comment]
we will update the tool in the next release. thank you !!

**Comment by LoayJabre** [comment]
Hi - How were you able to navigate this issue ? I'm trying to log into the submission tool, but I'm not really sure how to fix the proxy settings.
