### ISSUE TITLE
Problem uploading TIMS-TOF zipped data with PX v2.5.2

### ISSUE THREAD

**Issue by AidaSerra** [PRIDE-Archive/px-submission-tool#120]
Hi,
We are trying to upload data generated with TIMS-TOF mass spectrometer using the PX v2.5.2. We have zipped every folder obtained from TIMS-TOF individually (but zip files are big in size, everyone is around 2Gb) and we need to upload around 10 of those big zipped files and results from searchers in excel files. We have tried to upload those zipped files and excel files, choosing RAW format for zipped files and SEARCH for excel files. We have tried two different computers and we got always the same problem. In step 3/10 Add Files, when we click on Next, it pop-up a small window telling Checking your files, please wait. At it is permanently at 0%. With this error we are not able even to generate the px submission file to upload the files by ftp, so PRIDE support team suggested us to post here or look for another repository....

Any help, suggestion will be much appreciated as we are on rush to get that data upload and submit a manuscript.

Best,

Aida
[px_submission.log](https://github.com/PRIDE-Archive/px-submission-tool/files/6399372/px_submission.log)

**Comment by selvaebi** [comment]
hi what tool are you using for zipping the files ?

**Comment by selvaebi** [comment]
Seems like the zipping is malformed

**Comment by AidaSerra** [comment]
Hi, thanks for your reply. I contacted a collaborator that has a TIMS-TOF instruments and they used to upload zipped files in *.7z format. I tried and it worked. other zip formats like *.zip or *.rar gave me problems.

Thanks

**Comment by selvaebi** [comment]
Thanks for the update. But zip works for us anyway will check on it.
