### ISSUE TITLE
Problem with using Aspera to upload your files

### ISSUE THREAD

**Issue by wangshisheng** [PRIDE-Archive/px-submission-tool#123]
Hi px teams,

When I use the px-submission-tool to upload my raw files to Pride, it always gets an error as below:
![image](https://user-images.githubusercontent.com/19953005/119113586-d39af100-ba57-11eb-96d2-da61d1e3ea6d.png)

Could anyone give some suggestions or solutions?

Thanks a lot.

Bests,
Shisheng

**Comment by ypriverol** [comment]
This is probably an error with the Aspera protocol. Please try to use the FTP instead, or contact pride-support@ebi.ac.uk for more support.
