### ISSUE TITLE
Dataset PXD006991 contains only mgf files as raw data

### ISSUE THREAD

**Issue by Ananth-Prakash** [PRIDE-Archive/px-submission-tool#129]
Hi team,

The dataset PXD006991 only consists of mgf files and .dat files and there are no .raw files or .mzML files in its FTP http://ftp.ebi.ac.uk/pride-archive/2018/11/PXD006991/

Could the tool be updated to catch such data submissions?

Thanks,
Ananth

**Comment by ypriverol** [comment]
Ananth, this was probably submitted with old version of the tool.
