### ISSUE TITLE
Upload error (Failed to get upload credentials)

### ISSUE THREAD

**Issue by levitsky** [PRIDE-Archive/px-submission-tool#134]
Hi everyone,

I'm trying to submit a dataset and at step 10 I get this error:
![image](https://user-images.githubusercontent.com/3358268/173040336-c289548a-c1cb-4087-a130-79807bc90f0e.png)

The console output says the same thing:

`2022-06-10 12:50:28,913 ERROR [AWT-EventQueue-0] u.a.e.p.g.f.SubmissionDescriptor [SubmissionDescriptor.java:275] Cannot connect to Protomexchange web service for login credentials, likely outbound traffic for port TCP 22 is blocked. Please contact your system administrators to fix this problem.`

I am in Russia, getting this error from two locations (home and work), on three versions of the tool (2.5.4 through 2.5.6) and also tried using a UK-located VPN. Nothing helps. How can I debug and/or fix this? Any suggestions are appreciated.

Previously we have successfully submitted data from the work location using the tool v2.5.4.

**Comment by ypriverol** [comment]
@levitsky is this error happening during the transfer step? or during login into the tool?

**Comment by levitsky** [comment]
Step 10, "Submission summary". I suppose that is where the transfer is supposed to start. I log in successfully at the first step.

**Comment by ypriverol** [comment]
By default, it will try to submit using `aspera`. However, you can switch in the config files to FTP directly. If the problem continues, please save the submission.px, and we can give you and FTP and you can use your own FTP client.

**Comment by levitsky** [comment]
Changing the protocol setting to `ftp` doesn't seem to change anything, unfotunately.

**Comment by ypriverol** [comment]
Please write an email to pride-support@ebi.ac.uk and we will give you and FTP location. Remember to save your submission.px

**Comment by DrJCWright** [comment]
I have emailed pride-support but just wanted to add that we are having the same problem at the ICR with this latest version of the submission tool.

**Comment by levitsky** [comment]
How log does it usually take to get a response? I sent a request 5 days ago (`[pride-support #591976]`)  and have not had a reply yet.

**Comment by levitsky** [comment]
It's been two weeks and I haven't heard back from PRIDE Support yet.

**Comment by DrJCWright** [comment]
@levitsky Have you retried the submission? I attempted again earlier this weekend and the connection/authentication issue has resolved itself.

**Comment by levitsky** [comment]
@DrJCWright thanks for the heads-up! Unfortunately, my issue still persists. I also tried updating the submission tool to 2.5.7.

**Comment by levitsky** [comment]
@selvaebi 
Right now with 2.5.7, as well as earlier with older versions, I get this error at step 10, "Submission Summary", after I accept the license and click the Submit button.

**Comment by levitsky** [comment]
I guess, but it asks for authorization when I open it in the browser. And with curl, I get:

```
$ curl http://www.proteomexchange.org/archive-submission-ws/submission/upload/aspera
{"timestamp":"2022-06-28T16:43:13.265+0000","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/archive-submission-ws/submission/upload/aspera"}
```

**Comment by selvaebi** [comment]
can you provide your username and password in the browser?

**Comment by levitsky** [comment]
Ah, of course. Here's what I get:

```{"method":"ASPERA","host":"hx-fasp-1.ebi.ac.uk","port":3301,"folder":"lev.levitsky_20220628_164715","dropBox":{"dropBoxDirectory":"/nfs/pride/drop/pride-drop-003","userName":"pride-drop-003","password":"<I am redacting this but let me know if I should show it to you. It's not my password, of course>"}}```

**Comment by levitsky** [comment]
I can and I get a JSON in response, but apparently I should not show it? My comment was deleted.

**Comment by selvaebi** [comment]
yeah i deleted it , if it passes the tool shoudnt have a problem in processing it , are you using any proxies ??

**Comment by levitsky** [comment]
No, I don't, but I don't know what my ISP may be doing.
As I mentioned before, I have tried using a VPN, but it didn't affect anything.
