### ISSUE TITLE
Issue with logging into submission tool

### ISSUE THREAD

**Issue by LoayJabre** [PRIDE-Archive/px-submission-tool#136]
I'm using PRIDE submission tool version 2.5.7 on a Linux machine and when I try to log in, I get the following error: 

"Are you connected to the Internet via a proxy?
You can manually update the proxy server details in config/config.props present in px-submission-tool folder"

Has anyone seen this before or knows how to fix it ? I tried changing some things in the config.props file, but I'm not really sure what I'm doing.

**Comment by selvaebi** [comment]
Can you please update to the latest submission tool from https://www.ebi.ac.uk/pride/markdownpage/pridesubmissiontool please.
