### ISSUE TITLE
Extra files upload option

### ISSUE THREAD

**Issue by Tobias-Ternent** [PRIDE-Archive/px-submission-tool#4]
Sometimes PRIDE users have to upload some extra data files to supplement a submission, e.g. missing MaxQuant text files. Although a PRIDE user could make a brand new submission again, this isn't time or effort efficient for the user, especially when facing the prospect of uploading lots of data again perhaps over a slow connection. For these cases, we offer a manual upload option to our private FTP or Aspera servers. This isn't always ideal because either a separate FTP client needs to be used, or the command line for Aspera, and users may not know how to use these things. Plus, the FTP directory structure is hidden, making it less user-friendly for non-technical people.

It would be easiest if there was an option for a manual data upload with the submission tool. This could use Aspera or FTP through the GUI, select, transfer, delete, list files easily, and send notifications when uploads are completed.

**Comment by mbdebian** [comment]
@Tobias-Ternent , isn't it possible to upload them as "other" files, being part of the submission process?

**Comment by Tobias-Ternent** [comment]
I don't mean 'other' files, sorry for the confusion, I mean a way to easily upload additional files as requested/required after a submission has been made.

This is arguably the 2nd most important feature the tool could have.

e.g. A user makes a 'partial' submission with 10 raw files and 9 search files. Before processing the submission into PRIDE, a curator would ask if 1 search file was missing perhaps? Say 1 file was indeed missing, what can be done then?
(1) Curator would need to setup a PRIDE private FTP/Aspera directory, forward the detais to the submitter, get the submitter to upload their file to the directory. Not as straight forward for the user, because the root parent directory is hidden, maybe the user isn't familiar/competent at all with FTP GUI tools, or the FTP or Aspera command line for uploading data. This is a lot of manual effort for both the curator, who is often over-burdened at peak times, and for the submitter, who is also overwhelmed by additional steps required externally to the submission tool. Finally the curator would need to manually update the submission with the extra file.
(2) Curator asks for them to submit their entire data again for processing the submission into PRIDE. Curator removes original submission, submitter makes a new submission from scratch. Again, extra manual effort on both sides.
(3) Curator process the submission into PRIDE, and asks the submitter if they want to fix their data then they need to:
(3a) submit everything again as a 'resubmission'.
(3b) manually upload to FTP/Aspera directory, and the curator needs to set this up, and forward the details to the submitter. Then the curator manually updates and resubmits the existing PX submission.
