### ISSUE TITLE
Recommend that wiff.scan files are submitted together with wiff files in SWATH-MS datasets

### ISSUE THREAD

**Issue by javizca** [PRIDE-Archive/px-submission-tool#91]
We cannot make it mandatory, but for SWATH-MS data, if wiff files are uploaded as RAW files, recommend that the corresponding wiff.scan files are uploaded as well, since both are essential for replicating SWATH experiments. Maybe a recommendation could pop-up if people click on "next" without providing the wiff.scan files.

**Comment by javizca** [comment]
In all cases (both DDA and SWATH), both wiff and wiff.scan files are paired together. So ideally, both should or must be included. At least a recommendation would be needed.

**Comment by javizca** [comment]
But maybe this could be made mandatory

**Comment by selvaebi** [comment]
ok I can make it mandatory

**Comment by selvaebi** [comment]
done in https://github.com/PRIDE-Archive/px-submission-tool/pull/92
