### ISSUE TITLE
Improvement on the shown info on the PX submission tool

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/px-submission-tool#98]
I'd be good if it is possible to show at all time the version of the PX submission tool on the tool, for example on the title bar, if possible. Since many users upload screenshot with their queries about the PX submission tool and the first thing to check is the version of the tool.

Thanks,
David
<img width="271" alt="tool_version" src="https://user-images.githubusercontent.com/38863291/88378242-877c1300-cd98-11ea-9d2f-eaf134c4d05a.PNG">

**Comment by ypriverol** [comment]
@selvaebi this is a great suggestion.
